import type { SheetWorkbook, StoredGoogleSheetsIntegration } from './sheet-sync.types.js';

export function demoSheetWorkbook(
  integration: StoredGoogleSheetsIntegration,
): SheetWorkbook {
  return {
    spreadsheetTitle: integration.spreadsheetTitle ?? 'Planilha de valores negociados',
    tables: {
      [integration.suppliersSheetName]: {
        name: integration.suppliersSheetName,
        values: [
          [
            'ID do Fornecedor',
            'CNPJ do Fornecedor',
            'Razao Social',
            'Nome Comercial',
            'Categoria Padrao',
            'Natureza da Operacao Padrao',
            'Metodo de Pagamento Padrao',
            'Centro de Custo Padrao',
            'Status',
            'Observacoes',
          ],
          [
            'FOR-DEMO-001',
            '43.043.093/0001-44',
            'Be Life Clinica e Ambulatorial LTDA',
            'Be Life',
            'Medicamentos',
            'Venda de mercadoria',
            'Boleto Bancario',
            'Farmacia',
            'Ativo',
            'Registro demonstrativo da sincronizacao.',
          ],
        ],
      },
      [integration.pricesSheetName]: {
        name: integration.pricesSheetName,
        values: [
          [
            'Fornecedor',
            'CNPJ',
            'Item Padronizado',
            'Unidade de Medida',
            'Valor Unitario Inicial',
            'Valor Unitario Negociado',
            'Categoria',
            'Centro de Custo',
            'Vigencia Inicial',
            'Vigencia Final',
            'Status',
            'ID do Preco',
          ],
          [
            'Be Life Clinica e Ambulatorial LTDA',
            '43.043.093/0001-44',
            'Kit de aplicacao',
            'UN',
            'R$ 1.500,00',
            'R$ 1.250,00',
            'Medicamentos',
            'Farmacia',
            '01/07/2026',
            '31/12/2026',
            'Ativo',
            'PRC-DEMO-001',
          ],
        ],
      },
      [integration.itemsSheetName]: {
        name: integration.itemsSheetName,
        values: [
          [
            'Numero do Pedido',
            'Data de Emissao da Nota Fiscal',
            'Fornecedor',
            'Categoria',
            'Descricao Geral da Compra',
            'Item',
            'Centro de Custo',
            'Quantidade',
            'Unidade de Medida',
            'Valor Unitario Inicial',
            'Valor Unitario Negociado',
            'Natureza da Operacao',
            'Metodo de Pagamento',
            'Numero da Nota Fiscal',
            'Status',
          ],
          [
            'PED-DEMO-SHEETS-001',
            '14/07/2026',
            'Be Life Clinica e Ambulatorial LTDA',
            'Medicamentos',
            'Compra demonstrativa importada da planilha',
            'Kit de aplicacao',
            'Farmacia',
            '2',
            'UN',
            'R$ 1.500,00',
            'R$ 1.250,00',
            'Venda de mercadoria',
            'Boleto Bancario',
            'NF-DEMO-001',
            'Finalizado',
          ],
        ],
      },
      [integration.installmentsSheetName]: {
        name: integration.installmentsSheetName,
        values: [
          ['Numero do Pedido', 'Data de Vencimento', 'Valor da Parcela'],
          ['PED-DEMO-SHEETS-001', '30/07/2026', 'R$ 2.500,00'],
        ],
      },
    },
  };
}
